version: '3.8'

services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=tictactoe.settings
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8001 tictactoe.asgi:application
    volumes:
      - static_volume:/home/app/web/tictactoe/staticfiles
      - media_volume:/home/app/web/tictactoe/mediafiles
    expose:
      - 8001
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/tictactoe/staticfiles
      - media_volume:/home/app/web/tictactoe/mediafiles
#      - .nginx/ssl:/home/app/web/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    restart: always
  redis:
    image: redis:6
    volumes:
      - redis_volume:/data
    restart: always
  celery:
    build:
      context: .
    command: celery --app tictactoe worker --loglevel=info
    depends_on:
      - db
      - redis
    restart: always
    working_dir: /home/app/web/tictactoe
    volumes:
      - ./tictactoe:/home/app/web/tictactoe
  celery-beat:
    build:
      context: .
    command: celery --app=tictactoe beat --loglevel=info
    depends_on:
      - db
      - redis
    restart: always
    working_dir: /home/app/web/tictactoe
    volumes:
      - ./tictactoe:/home/app/web/tictactoe
volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_volume:
