# Generated by Django 4.2.17 on 2025-01-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_updated_alter_user_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
