# Generated by Django 4.2.17 on 2025-01-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_skill_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.jpg', null=True, upload_to='media/avatars/'),
        ),
    ]
