# Generated by Django 4.2.17 on 2024-12-26 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_gameroom_code_alter_gameroom_game_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player_o',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_y', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player_x',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_x', to=settings.AUTH_USER_MODEL),
        ),
    ]
