# Generated by Django 4.2.17 on 2024-12-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_gameroom_player_o_gameroom_player_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='player_o',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_y', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_x',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_x', to=settings.AUTH_USER_MODEL),
        ),
    ]
