# Generated by Django 4.2.17 on 2024-12-26 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_gameroom_player_o_alter_gameroom_player_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgame',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
