# Generated by Django 4.2.17 on 2025-01-05 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_playedgame_player_o_playedgame_player_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_o',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_o', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='player_o',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='history_player_o', to=settings.AUTH_USER_MODEL),
        ),
    ]
