# Generated by Django 4.2.17 on 2025-01-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gameroom_game_started_alter_gameroom_player_o_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.CharField(max_length=50),
        ),
    ]
