# Generated by Django 4.2.17 on 2025-01-21 10:29

import apps.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_gameroom_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameroom',
            options={'verbose_name': 'Game Room', 'verbose_name_plural': 'Game Rooms'},
        ),
        migrations.AlterModelOptions(
            name='playedgame',
            options={'verbose_name': 'Played Game', 'verbose_name_plural': 'Played Games'},
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='code',
            field=models.CharField(default=apps.api.models.generate_unique_code, help_text='Unique identifier for the game room.', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the room was created.'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='game_option',
            field=models.CharField(default='r', help_text="Game option: 'r' for random, 'x' for Player X, 'o' for Player O.", max_length=1),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='game_started',
            field=models.BooleanField(default=False, help_text='Whether the game has started.'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.CharField(help_text='Session key of the host of the game room.', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_o',
            field=models.ForeignKey(blank=True, default=None, help_text='The user playing as O in the room.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='active_games_as_o', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_x',
            field=models.ForeignKey(blank=True, default=None, help_text='The user playing as X in the room.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='active_games_as_x', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='code',
            field=models.CharField(default=apps.api.models.generate_unique_code, help_text='Unique identifier for the played game.', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the game was created.'),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Whether the game has been completed.'),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='player_o',
            field=models.ForeignKey(blank=True, default=None, help_text='The user who played as O.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='games_as_o', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='player_x',
            field=models.ForeignKey(blank=True, default=None, help_text='The user who played as X.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='games_as_x', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playedgame',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, help_text='The user who won the game.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
